#!/usr/bin/env bash
# vboot_anchor_header.sh — emit the C trust-anchor header (the 32-byte Ed25519
# public key) from an EXISTING private key. Used by both the CI smoke test
# (ephemeral key) and a real release (offline key), so the build compiles in the
# public half matching whatever key will sign the image.
#
# Usage: vboot_anchor_header.sh <private_key.pem> <out_anchor_header.h>
set -euo pipefail

PRIV="${1:?usage: vboot_anchor_header.sh <priv.pem> <anchor.h>}"
HDR="${2:?usage: vboot_anchor_header.sh <priv.pem> <anchor.h>}"

mkdir -p "$(dirname "$HDR")"

# Raw 32-byte public key: the Ed25519 SubjectPublicKeyInfo DER is a fixed 44-byte
# structure whose last 32 bytes are the raw public key.
PUB_HEX=$(openssl pkey -in "$PRIV" -pubout -outform DER 2>/dev/null | tail -c 32 | od -An -tx1 | tr -d ' \n')

if [ "${#PUB_HEX}" -ne 64 ]; then
    echo "vboot_anchor_header: expected 64 hex chars (32 bytes) of public key, got ${#PUB_HEX}" >&2
    exit 1
fi

{
    echo "/* GENERATED by tools/vboot_anchor_header.sh — do not edit, do not commit. */"
    echo "/* Ed25519 trust anchor (public key) for VBOOT_ENFORCE verified boot. */"
    echo "#ifndef VBOOT_ANCHOR_H"
    echo "#define VBOOT_ANCHOR_H"
    echo "static const uint8_t VBOOT_ANCHOR_PUBKEY[32] = {"
    printf '    '
    for i in $(seq 0 31); do
        byte=${PUB_HEX:$((i*2)):2}
        printf '0x%s, ' "$byte"
        if [ $(((i + 1) % 8)) -eq 0 ]; then printf '\n    '; fi
    done
    echo ""
    echo "};"
    echo "#endif /* VBOOT_ANCHOR_H */"
} > "$HDR"

echo "vboot_anchor_header: wrote $HDR"
